### ISSUE TITLE
Problem when chunk return 2 plots

### ISSUE THREAD

**Issue by dfalbel** [rstudio/blogdown#8]
If you add a chunk that results in 2 plots, like this 

    ```{r test, fig.show='hold', out.width="50%"}
    library(ggplot2)
    ggplot(mtcars) + geom_point(aes(x = mpg, y = disp))
    ggplot(mtcars) + geom_point(aes(x = mpg, y = disp))
    ```

You will get this warning when serving the site:

```
Warning messages:
1: In file.create(to[okay]) :
  cannot create file './post/hello-world/figures', reason 'Is a directory'
2: In file.create(to[okay]) :
  cannot create file './post/hello-world/figures', reason 'Is a directory'
```

Then both images are not displayed. When you re-serve the site it works, but if you erase the public directory it will happen again. This happens directly when using `blogdown::new_site()` and you add the chunk to the sample post.

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!

**Comment by dfalbel** [comment]
Sorry, It's still happening for me
I found that in fact, you need to erase the generated `.html` in `content` folder for it to re-happen.

```
> blogdown::serve_site()
Started building sites ...
Built site for language en:
0 draft content
0 future content
0 expired content
1 pages created
3 non-page files copied
2 paginator pages created
0 tags created
0 categories created
total in 52 ms

Warning messages:
1: In file.create(to[okay]) :
  cannot create file './post/hello-world/figures', reason 'Is a directory'
2: In file.create(to[okay]) :
  cannot create file './post/hello-world/figures', reason 'Is a directory'
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.7        rstudioapi_0.6     servr_0.4.1        knitr_1.15        
 [5] magrittr_1.5       devtools_1.12.0    xtable_1.8-2       R6_2.2.0          
 [9] stringr_1.1.0      httr_1.2.1         tools_3.3.1        miniUI_0.1.1      
[13] git2r_0.15.0       withr_1.0.2        htmltools_0.3.5    yaml_2.1.13       
[17] digest_0.6.10      rprojroot_1.1      bookdown_0.1.20    shiny_0.14        
[21] rsconnect_0.5      curl_1.2           memoise_1.0.0      evaluate_0.10     
[25] mime_0.5           rmarkdown_1.1.9016 blogdown_0.0.4     stringi_1.1.1     
[29] backports_1.0.4    httpuv_1.3.3      
```

**Comment by dfalbel** [comment]
Maybe it wasn't a clean session, because it it's working now! sorry!!
